name: test action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    test:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9' # Or your desired version

      - name: Install dependencies
        run: | 
                pip install -r requirements.txt
                pip install pytest-playwright

            - name: Install Playwright browsers
              run: playwright install --with-deps

            - name: Run Playwright tests
              run: pytest  # Or pytest <test_directory> if needed

            - name: Publish Test Results
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: playwright-report
                path: test-results # Or your test results directory